import assert from 'node:assert/strict';
import {workflowAction,workflowChange} from '../static/submissions.js';
const values={'import-namespace':'A','import-sheet':'0','import-header':'1','import-asset':'asset-A','import-col-key':'0','import-col-title':'1','import-col-text':'2','import-col-target':'3'};
globalThis.document={getElementById:id=>({value:values[id]}),querySelectorAll:()=>[]};
let resolvePreview,submitted;
const ctx={actor:{id:'actor'},state:{id:'catalog'},importSpec:{},busy(){},showModal(){},closeModal(){},render(){},notify(){},api(path,method,data){if(path.endsWith('preview'))return new Promise(r=>resolvePreview=r);submitted=data;return Promise.resolve({id:'catalog'});}};
const pending=workflowAction(ctx,'workflow-import-preview',{});
assert.equal(ctx.workflowPending,true);
values['import-sheet']='1';
assert.equal(workflowChange(ctx,{id:'import-sheet'}),false);
ctx.importSpec={sheet:1,asset_id:'asset-B'};
resolvePreview({version:9,namespace:'A',sheet_name:'A',counts:{},missing_keys:[],errors:[],rows:[],note:''});
await pending;
await workflowAction(ctx,'workflow-import-apply',{});
assert.equal(submitted.operation.sheet,0);
assert.equal(submitted.operation.asset_id,'asset-A');
assert.equal(submitted.version,9);
ctx.state.id='another-catalog';
await assert.rejects(workflowAction(ctx,'workflow-import-apply',{}),/もう一度/);
console.log('PASS: preview snapshot, in-flight lock, catalog identity');
