import assert from 'node:assert/strict';
import {libraryHTML,campaignsHTML} from '../static/library.js';
const ctx={actor:{role:'developer'},libraryBooks:[{id:'a',title:'<script>A</script>',version:1,page_count:2}],libraryResult:{query:'X',occurrence_count:2,target_count:1,catalogs:[],scope:'scope',results:[{catalog_id:'a',title:'Book',element_id:'e',page_id:'p',page_label:'1',order:1,revision:1,context:'<img>',placement_status:'要確認'}]}};
let html=libraryHTML(ctx);assert.match(html,/&lt;script&gt;/);assert.doesNotMatch(html,/data-library-target=/);assert.doesNotMatch(html,/選択対象と指示を確認/);
ctx.actor.role='editor';html=libraryHTML(ctx);assert.match(html,/data-library-target="0"/);assert.match(html,/紙面/);
ctx.campaignList=[{id:'c',title:'Change',query:'X',instruction:'test',counts:{open:1,fixed:0,verified:1,recheck:0,missing:0},complete:false,targets:[]}];
assert.match(campaignsHTML(ctx),/対応中/);assert.doesNotMatch(campaignsHTML(ctx),/選択対象は全て確認済み/);
console.log('PASS: staff permissions, explicit targets, escapes, partial-completion label');
import {captureLibraryDraft} from '../static/library.js';
const fields={'campaign-title':{value:'価格改訂'},'campaign-instruction':{value:'長い指示を保存'}};
globalThis.document={getElementById:id=>fields[id],querySelectorAll:()=>[{dataset:{libraryTarget:'0'}}]};
captureLibraryDraft(ctx);
html=libraryHTML(ctx);assert.match(html,/価格改訂/);assert.match(html,/長い指示を保存/);assert.match(html,/data-library-target="0" checked/);
globalThis.document={getElementById:()=>null};captureLibraryDraft(ctx);
assert.equal(ctx.libraryDraft.instruction,'長い指示を保存');
console.log('PASS: instruction and target selection survive paper navigation');
import {refreshCampaigns} from '../static/library.js';
let rendered='';const progress={actor:{role:'editor'},campaignList:[{complete:true}],render(){rendered=campaignsHTML(this)},api:async()=>{throw new Error('offline')}};
await assert.rejects(()=>refreshCampaigns(progress),/offline/);
assert.doesNotMatch(rendered,/選択対象は全て確認済み/);assert.match(rendered,/進捗を取得できません/);
progress.api=async()=>[];await refreshCampaigns(progress);assert.match(rendered,/変更案件はまだありません/);
console.log('PASS: failed refresh clears stale completion and offers retry');
