import assert from 'node:assert/strict';
import {readFileSync} from 'node:fs';
import vm from 'node:vm';
import {pageSelect,developerPlanHTML,hasSubmissionDraft} from '../static/intake_pages.js';
const ctx={actor:{role:'developer'},state:{id:'A',document:{pages:[{id:'new',title:'新製品',elements:[],original:false}]},submissions:[{id:'s',title:'原稿',page_id:'new'}],attachments:[]}};
const plan=developerPlanHTML(ctx);
assert.match(plan,/このページの原稿を登録/);assert.match(plan,/原稿 1件/);
assert.doesNotMatch(plan,/data-act="(?:delete-page|order-page|rename-page|new-page)"/);
assert.match(pageSelect(ctx,'target','removed'),/value="removed" selected disabled/);
assert.match(pageSelect(ctx,'target','removed'),/選び直してください/);
ctx.submissionDraft={text:'Aの未保存原稿',page_id:'A-page'};
assert.equal(hasSubmissionDraft(ctx),true);
const code=readFileSync(new URL('../static/app.js',import.meta.url),'utf8');
const upload=code.slice(code.indexOf('async function upload('),code.indexOf('\nfunction previewAsset'));
ctx.api=async path=>path==='/api/catalogs'?{id:'B',document:{pages:[{id:'B-page'}]},attachments:[]}:[];
const sandbox={ctx,confirm:()=>true,captureSubmissionDraft(){},hasSubmissionDraft,busy(){},readFile:async()=>'',render(){},notify(){}};
vm.createContext(sandbox);vm.runInContext(upload,sandbox);
await sandbox.upload([{name:'B.idml'}],true);
assert.equal(ctx.state.id,'B');assert.equal(hasSubmissionDraft(ctx),false);
assert.equal(ctx.submissionDraft.page_id,undefined);
console.log('PASS: developer plan controls, removed-page selection, import draft isolation');
